---
title: "Manuscript Outline:Spatio-Temporal Distribution of Atlantic Menhaden Project"
author: "Janelle Morano"
date: "last updated 8/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Quantifying Spatio-Temporal Responses of Marine Ecosystems to Climate Change and Other Anthropogenic Habitat Modifications to Facilitate Adaptive Management Strategies

Janelle L. Morano^1^, Patrick J. Sullivan^1^, Kevin Friedland^2^

Addresses:
^1^Department of Natural Resources and the Environment, Cornell University, Ithaca, NY 14850
^2^National Marine Fisheries Service, Narragansett, RI

_Should considering inviting Rob Latour and Jason McNamee._

# Abstract

Marine species are responding to dramatic changes in the marine environment caused by climate change through adaptation, mortality, or movement. When properly characterizing the spatio-temporal distribution and abundance of species, we reveal the underlying ecosystem processes and dynamics that influence species populations and community dynamics. Accounting for these processes can reduce the bias in existing population models and improve the accuracy of predicting species distributions under future seascape scenarios (e.g., climate change scenarios, offshore wind development). The accuracy and precision of spatio-temporal distributions are best identified with species distribution models (SDM) that account for unmeasured variables and processes (i.e. latent variables or random effects), including spatial autocorrelation (neighboring samples are more similar to each other than those that are farther apart). These models can also be used to explore and address situations where species may not be appropriately captured by a fixed survey, either temporally or spatially, as a result of a changing ecosystem. For example, species movements to deeper waters, latitudinal shifts outside a survey region, or shifts in the timing of seasonal migrations. Forage fish (juvenile fish and small pelagic fishes) are important prey for large pelagic and protected species; their populations are sensitive to environmental conditions, but their spatial distributions are often overlooked. Using Atlantic menhaden, Brevoortia tyrannus, as a case study, we assessed the spatio-temporal distribution of menhaden along the US east coast using multiple fisheries-independent surveys and abiotic data in spatio-temporal models. We considered trade-offs in model architecture and different surveys to the spatio-temporal predictions at various scales. We evaluated options for alternative sampling designs and modeling architectures to support adaptive management strategies and future planning efforts.

# Introduction
Atlantic menhaden are a planktivorous schooler found in coastal waters from Florida to Nova Scotia and important prey to fish, birds, and marine mammals. Occurrence data from the NEFSC spring and fall bottom trawl indicate that menhaden are found in the NY Bight (**ADD FIGURE**). Menhaden spend the winter in warmer offshore waters off the southeastern US coast, then move north in spring (Nicholson, 1978). In the summer, they stratify and school by age/size, where older fish move farther north (Nicholson, 1978). Adults in the north migrate south beginning in late summer (Nicholson, 1978; Simpson et al., 2016). Coastal schools disperse by January until reforming in spring (Ahrenholz, 1991).

Spawning occurs all along the east coast, offshore and near-shore in hotspots between Chesapeake Bay and Delaware and near Long Island, throughout the year, except July and August,  (Simpson et al., 2017). Spawning occurs between 12–25 °C (Hettler, 1981; Stegmann et al., 1999), and so seasonality of spawning depends on the location, where spawning occurs in the summer in the North Atlantic, in the spring and fall in mid-Atlantic, and in the winter in the south (Nicholson, 1964). Eggs hatch at sea and larvae are transported and settle in estuaries to the south of where spawning has occurred (Stegmann et al., 1999). Larvae have the highest abundance near North Carolina in November and December (Simpson et al., 2016). Atlantic menhaden exhibit recruitment variations with distinct spatial patterns between the Chesapeake Bay and southern New England regions (Buchheister et al., 2016)

Following a peak in the late 1950s, adult abundance declined through the 1960s. Abundance increased in the late 1970s through the mid-1990s, and decreased through the 2000s (**ADD FIGURE**). In 2017, adult abundance was relatively high, yet juvenile abundance was low. Larval abundance increased from 1977 to 2013, corresponding closely with adult spawning stock biomass. Cooler temperatures, intermediate wind speeds, and negative-phase AMO were most favorable for larval abundance (Simpson et al., 2016). Abundance patterns across the coast are not temporally even, where increased abundance was in the south in the 70s-90s, then in the north in the early 2000s (Buchheister et al., 2016).

Menhaden are commercially caught for fish meal and oil and as bait, and is the largest fishery on the US east coast (Alder et al., 2008). The most recent stock assessment was in 2020 and uses a model that accounts for its role as a forage fish, primarily for striped bass as ecological reference points due to striped bass’ sensitivity to menhaden harvest (SEDAR, 2020). 

There is an unusual mortality event of humpback whales, a protected species, along the US east coast since 2016 (see also https://www.fisheries.noaa.gov/national/marine-life-distress/2016-2020-humpback-whale-unusual-mortality-event-along-atlantic-coast). Additionally, there has been an anecdotal increase in Atlantic menhaden schools nearshore within the NY Bight. Biomass by sample site data from NEFSC spring and fall bottom trawl surveys indicate that there may be data to support the anecdotal accounts (Figure 9). Since humpbacks feed on menhaden, NYSDEC is interested in the relationship between menhaden and humpback abundance and distribution.

Spatio-temporal analyses of menhaden distribution are available in the 2020 stock assessment. The 2020 stock assessment included an analysis of the habitat preference and occurrence probability. Using a generalized additive mixed model (GAMM) with annual bottom temperature, annual bottom salinity, depth, and survey type (as a proxy for catchability) as fixed effects, and year as random effect, bottom temperature was the most important predictor of catch-per-unit-effort (CPUE). A random forest model was used to construct habitat variables on a grid and predict the occurrence probability across menhaden distribution, showing that menhaden are on continental shelf in the spring. Given the data available for marine distribution, it is possible to assess the spatio-temporal distribution of menhaden in the NY Bight and make predictions for distribution in the future. 

# Methods

## Data
NEFSC bottom trawl data.

## Spatio-temporal models
### GAMM

### R-INLA

### VAST

# Results

# Conclusions

# Acknowledgements

