---
title: "Background"
author: "Janelle Morano"
date: "`r format(Sys.time(), '%d %b %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Atlantic menhaden, *Brevoortia tyrannus*
* planktivorous schoolers found in coastal waters from Florida to Nova Scotia
* spend the winter off the southeastern US coast and move north in spring
* summer: stratify and school by age/size, and older fish move farther north
* late summer: migrate south again
* Menhaden migration and spawning is closely associated water temperature XX range
* Menhaden feed on phyto- and zooplankton as juveniles and young adults until XX size
* Menhaden abundance peaked in the 1950s and then decreased precipitously, maintaining a relatively low abundance through the 1980s. Since the 1990s, abudance has trended to increase, with abudance in recent years being more similar to the 1950s
* Spatially, abundance patterns across the coast are not temporally even, where increased abundance was in the south in the 70s-90s, then in the north in the early 2000s
* anecdotal evidence that menhaden abundance has increased in the NY Bight region in recent years.
